services:
    frontend_user:
        build: ./FE/User
        ports:
            - 3001:3001
        volumes:
            - ./FE/User:/RMS/FE/User
            - /RMS/FE/User/
              node_modules        
