services:
    db_postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=RMS
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8000:8080
        environment:
            - ADMINER_DEFAULT_SERVER=db_postgres

    backend_internal:
        build: ./BE/Internal
        depends_on:
            - db_postgres
        ports:
            - 3003:3003
        environment:
            - DB_HOST=db_postgres
        volumes:
            - ./BE/Internal/migrations:/RMS/BE/Internal/migrations
            - ./BE/Internal/seeders:/RMS/BE/Internal/seeders
            - ./BE/Internal/src:/RMS/BE/Internal/src
            - ./BE/Internal/swagger:/RMS/BE/Internal/swagger
            - ./BE/Internal/tests:/RMS/BE/Internal/tests
            - ./BE/Internal/.env:/RMS/BE/Internal/.env
            - ./BE/Internal/.sequelizerc:/RMS/BE/Internal/.sequelizerc
            - ./BE/Internal/jest.config.ts:/RMS/BE/Internal/jest.config.ts
            - ./BE/Internal/tsconfig.json:/RMS/BE/Internal/tsconfig.json
            - /RMS/BE/Internal/node_modules

    backend_external:
        build: ./BE/External
        ports:
            - 8080:8080
        volumes:
            - ./BE/External:/RMS/BE/External
        dns:
            hostname:localhost
    
    frontend_user:
        build: ./FE/User
        depends_on:
            - backend_internal
        ports:
            - 3001:3001
        volumes:
            - ./FE/User:/RMS/FE/User
            - /RMS/FE/User/node_modules
        environment:
            - NEXT_PUBLIC_BACKEND_NAME=backend_internal
    
    frontend_admin:
        build: ./FE/admin
        depends_on:
            - backend_internal
        ports:
            - 3000:3000
        volumes:
            - ./FE/admin:/RMS/FE/admin
            - /RMS/FE/admin/node_modules
        environment:
            - NEXT_PUBLIC_BACKEND_NAME=backend_internal

        