services:
    frontend_admin:
        build: ./FE/admin
        ports:
            - 3000:3000
        volumes:
            - ./FE/admin:/RMS/FE/admin
            - /RMS/FE/admin/node_modules
        environment:
            - NEXT_PUBLIC_BACKEND_NAME=backend_internal

        
