export const clientUser = {
    email: "client@example.com",
    phone: "0123456789",
    firstname: "Nguyen",
    lastname: "Hung",
    gender: false,
    birthday: new Date(),
    avatar: "",
    score: 0,
    address: "",
    source: "",
    type: "",
    hashedPassword: "client",
    isRegistered: false,
    isActive: true,
    language: "vi",
    profit: 0,
    average: 0,
    total_items: 0,
};