import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Sidebar} from '@/components/Sidebar'
import {Header} from '@/components/Header'
import '../globals.css'
import Colors  from '@/app/variables.module.scss'
import { ReactNode } from 'react'
import { NextIntlClientProvider, useMessages } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
    children?: ReactNode
    params: any
}

 

export default function LocaleLayout({children, params: {locale}}: Props) {

    // const isValidLocale = locales.some((cur) => cur === locale);
    // if (!isValidLocale) notFound();
    const messages = useMessages();
    return (
        <html lang={locale} >
            <body className={inter.className} suppressHydrationWarning={true}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <div className="flex relative" style={{backgroundColor: Colors.defaultBackgroundColor }}>
                    <Sidebar />
                    <div className="main-content flex-1">
                        <Header />
                        {children}
                    </div>
                </div>
            </NextIntlClientProvider>
            </body>
        </html>
  )
}
