import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Sidebar} from '@/components/Sidebar'
import {Header} from '@/components/Header'
import '../globals.css'
import Colors  from '@/app/variables.module.scss'
import { ReactNode } from 'react'
import { NextIntlClientProvider, useLocale, useMessages } from 'next-intl'
import { headers } from 'next/headers';
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RMS',
  description: 'Generated by create next app',
}

interface LocaleLayoutProps {
    children: ReactNode;
    params: {
        locale: string;
    };
}

 

export default function LocaleLayout({children, params}: LocaleLayoutProps) {

    const header = headers();
    const localeHeader = header.get('x-next-intl-locale');
    if (localeHeader === null) {
        notFound();
    }

    const locale = useLocale();
    const messages = useMessages();
    console.log(locale, params.locale)

    // Validate that the incoming `locale` parameter is a valid locale
    if (params.locale !== locale) {
        notFound();
    }

    return (
        <html lang={locale} >
            <body className={inter.className} suppressHydrationWarning={true}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <div className="flex relative" style={{backgroundColor: Colors.defaultBackgroundColor }}>
                    <Sidebar />
                    <div className="main-content flex-1">
                        <Header />
                        {children}
                    </div>
                </div>
            </NextIntlClientProvider>
            </body>
        </html>
  )
}
